### ISSUE TITLE
A even better downloader enablement mechanism 

### ISSUE THREAD

**Issue by CXwudi** [CXwudi/vocadb-video-downloader-new#18]
Currently, no way for us to config two same downlaoders with different command line for even same pv service.
[#1]

So in `config.downloader`, instead of having each pv service listing all available downloaders, lets it be a list of config with name. And the enablement will use the name as the order of downloaders for that pv service. 

[vocadb-video-downloader-new] vvd-downloader/src/main/resources/application.yml (Lines 34-65)

```

  # which PV service uses which downloader(s), separated by comma
  # downloader names must be same as names in downloader setting
  # when new PV service is added, change it on DownloaderBaseConfig
  enablement:
    NicoNicoDouga:  # enable downloaders from NicoNicoDouga's available downloaders. e.g. nndownload
    Youtube:
    Bilibili:


  downloader:
    NicoNicoDouga:
      # settings of youtube-dl/ytp-dl for downloading niconico videos
      # settings must make sure nothing blocks from downloading the video (e.g. don't put --version on yt-dlp)
      # do the same for all other downloaders.
      youtube-dl:
        launch-cmd:
        external-args:

      nndownload:
        launch-cmd:
        external-args:

    Youtube:
      youtube-dl:
        launch-cmd:
        external-args:

    Bilibili:
      youtube-dl:
        launch-cmd:
        external-args:

```

[Open in IDE](https://api.codestream.com/c/YLLEz_X_ViemfnDX/kXpIB2-2QR6YAKPbIFVP1Q?marker=61a046bb1ee5c8449c90fcc8&ide=default&src=GitHub) · [Open on GitHub](https://github.com/cxwudi/vocadb-video-downloader-new/blob/18c06710b25d311bb10bad7b7ce892280d594f0a/vvd-downloader/src/main/resources/application.yml#L34-L65)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
