### ISSUE TITLE
A way better sorting and enablement for PVs

### ISSUE THREAD

**Issue by CXwudi** [CXwudi/vocadb-video-downloader-new#92]
The current way of sorting and filtering PVs are sucks and buggy. Here is a way better mechanism:

``` yaml
config:
	preference:
		# a list of <PvService>.<PvType>
		chosen-pvs: NicoNicoDouga.Original, NicoNicoDouga.Reprint, NicoNicoDouga.Other, Youtube.Original, Youtube.Reprint, Youtube.Other, Bilibili.Original, Bilibili.Reprint, Bilibili.Other
```

This single option can cover two old options: `try-reprinted-pv` and `try-all-original-pvs-before-reprinted-pvs`
